name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to MatchBox!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which area does this relate to?
      options:
        - Wazuh (Manager/Dashboard/Agent)
        - OpenCTI
        - TheHive / Cortex
        - Monitoring (Grafana/Prometheus)
        - MCP Servers
        - Automation Scripts
        - Dashboard UI
        - Documentation
        - Infrastructure (k3s/Lima)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
